project_id = "bdeotnzldfnqwbdymscp"

[functions.french-feedback]
verify_jwt = false

[functions.french-chat]
verify_jwt = false

[functions.language-feedback]
verify_jwt = false

[functions.language-chat]
verify_jwt = false

[functions.reflection]
verify_jwt = false

[functions.generate-embedding]
verify_jwt = false
